routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [
    'uses'=>'PagesController@home',
    'as'=>'home']);
Route::get('/about', [
    'uses'=>'PagesController@about',
    'as'=>'about']);
Route::get('/contact',[
    'uses'=>'PagesController@contact',
    'as'=> 'contact']);

Route::group(['prefix'=>'task','as'=>'task'],function() {
    Route::get('', [
        'uses' => 'TaskController@index',
        'as' => '']);
    Route::post('', [
        'uses' => 'TaskController@store',
        'as' => '.store']);
    Route::get('/create', [
        'uses' => 'TaskController@create',
        'as' => '.create']);
    Route::get('/{task}/edit', [
        'uses' => 'TaskController@edit',
        'as' => '.edit']);
    Route::patch('/{task}', [
        'uses' => 'TaskController@update',
        'as' => '.update']);
    Route::delete('/{task}', [
        'uses' => 'TaskController@delete',
        'as' => '.delete']);
});

Route::group(['prefix'=>'week', 'as'=>'week.'], function(){

    Route::get('/',[
        'uses'=>'WeekController@index',
        'as'=>'']);
    Route::post('/',[
        'uses'=>'WeekController@store',
        'as'=>'store']);
    Route::get('/create',[
        'uses'=>'WeekController@create',
        'as'=>'create']);
    Route::get('/{week}/edit',[
        'uses'=>'weekController@edit',
        'as'=>'edit']);
    Route::get('/{week}',[
        'uses'=>'WeekController@show',
        'as'=>'show']);
});

Route::group(['prefix'=>'week/{week}/task', 'as'=>"weekTask"], function(){

    Route::post('/',[
        'uses'=>'WeekTaskController@store',
        'as'=> '']);
});


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/PagesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class PagesController extends Controller
{
    public function home()
    {
        return view ('welcome');
    }

    public function about()
    {
        return view('about');
    }

    public function contact ()
    {
        return view('contact');
    }
}

app/Http/Controllers/TaskController.php
<?php

namespace App\Http\Controllers;


use App\Domain\Repositories\TaskRepositoryInterface;
use Illuminate\Http\Request;
use App\Domain\Task;
use Illuminate\Support\Facades\Auth;

class TaskController extends Controller
{
    private $taskRepository;

    public function __construct(TaskRepositoryInterface $taskRepository)
    {
        $this->taskRepository = $taskRepository;
        $this->middleware('auth');
    }

    public function index ()
    {
        $tasks = $this->taskRepository->getAllTasks();
        return view ('Tasks/index', compact('tasks'));
    }

    public function create()
    {
        return view ('Tasks/create');
    }

    public function store()
    {

       $input= $this->validateTask();

        $this->taskRepository->createTask($input);

        return redirect(route('week/{$id}'));
    }

    public function edit($id)
    {
        $task= $this->taskRepository->getTaskById($id);

        abort_if(auth()->user() !== $task->getUser(),403);

        return view('Tasks/edit', compact('task'));
    }

    public function update ($id)
    {
        $input= $this->validateTask();
        $input['completed'] = (request()->has('completed'));
        $input['remarks']= request('remarks');
        $this->taskRepository->updateTask($id, $input);

        $weekId=$this->taskRepository->getTaskById($id)->getWeek()->getId();
        return redirect (route('week.show',['$id'=>$weekId]));
    }

    public function delete ($id)
    {
        $weekId=$this->taskRepository->getTaskById($id)->getWeek()->getId();
        $this->taskRepository->deleteTask($id);

        return redirect (route('week.show',['$id'=>$weekId]));
    }

    private function validateTask()
    {
        return request()->validate([
            'title' =>['required', 'min:3'],
            'description' =>['required', 'min:10'],
            'remarks' => ['nullable', 'min:10']
        ]);
    }

}

app/Http/Controllers/WeekController.php
<?php

namespace App\Http\Controllers;

use App\Domain\Repositories\WorkWeekRepositoryInterface;
use Illuminate\Http\Request;


class WeekController extends Controller
{
    private $WorkWeekRepository;

    public function __construct(WorkWeekRepositoryInterface $WorkWeekRepository)
    {
        $this->WorkWeekRepository=$WorkWeekRepository;
        $this->middleware('auth')->only(['show']);
    }

    public function index()
    {
        $weeks=$this->WorkWeekRepository->getAllWeeks();

        return view('Weeks/index', compact('weeks'));
    }

    public function create()
    {
        return view('Weeks/create');
    }

    public function show ($id)
    {

        $week=$this->WorkWeekRepository->getWeekById($id);

        //dd($week->getTasks());

        return view('Weeks/show', compact('week'));
    }

    public function store ()
    {
        $input=request()->validate([
            'weekNumber'=>['required', 'integer'],
            'startDate' =>['required', 'date'],
            'endDate'=>['required', 'date']
            ]);

        $weekId= $this->WorkWeekRepository->createWeek($input);

        return redirect(route('week.show',['$id'=> $weekId]));
    }
}

app/Http/Controllers/WeekTaskController.php
<?php

namespace App\Http\Controllers;

use App\Domain\Repositories\TaskRepositoryInterface;
use App\Domain\Repositories\WorkWeekRepositoryInterface;
use App\Domain\WorkWeek;
use Illuminate\Http\Request;

class WeekTaskController extends Controller
{
    private $taskRepository;
    private $weekRepository;

    public function __construct(
        TaskRepositoryInterface $taskRepository,
        WorkWeekRepositoryInterface $workWeekRepository)
    {
        $this->taskRepository=$taskRepository;
        $this->weekRepository=$workWeekRepository;
        $this->middleware('auth');
    }

    public function store($weekId)
    {
        $user= auth()->user();

        $input=request()->validate([
            'title' =>['required', 'min:3'],
            'description' =>['required', 'min:10']
        ]);
        $input['week']=$this->weekRepository->getWeekById($weekId);
        $input['user']=$user;

        $this->taskRepository->createTask($input);

        return redirect(route('week.show',[$id=$weekId]));
    }
}

resources/views/Tasks/create.blade.php
@extends('partials/layout')

@section('title')
    Create task
@endsection

@section ('content')
<div class="container" >
    <div class="row">
        <div class="col-lg-2">
            <form method="post" action="{{route('task.store')}}">
                @csrf
                <div class="form-group">
                    <label >Title </label>
                    <input type="text" name="title" class="form-control" required>
                </div>
                <div class="form-group">
                    <label >Description </label>
                    <input type="text" name="description" class="form-control" required>
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-success">Create task</button>
                </div>
                @include('partials.errors')
            </form>
        </div>
    </div>
</div>

@endsection

resources/views/Tasks/edit.blade.php
@extends ('partials.layout')

@section('title')
   Edit task
@endsection

@section ('content')
    <div class="container" >
        <div class="row">
            <div class="col-lg-6">
                <form method="post" action="{{route('task.update',['id'=>$task->getId()])}}">
                    @csrf
                    @method("patch")
                    <div class="form-group">
                        <label >Title </label>
                        <input type="text" name="title" class="form-control"value="{{$task->getTitle()}}" required >
                    </div>
                    <div class="form-group">
                        <label >Description </label>
                        <textarea type="text" name="description" class="form-control" required>{{$task->getDescription()}}  </textarea>
                    </div>
                    <div class="form-group">
                        <label class="custom-checkbox" for="completed">Completed </label>
                        <input type="checkbox" name="completed" {{$task->getCompleted()? 'checked':'' }} >
                    </div>
                        <div class="form-group">
                            <label class="form-group">Remarks when completed</label>
                            <textarea type="text" name="remarks" class="form-control" {{$task->getRemarksCompleted()}}> </textarea>
                        </div>
                    <div class="form-group">
                        <button type="submit" class="btn btn-success">Update task</button>
                    </div>
                </form>
                <form method = "post" action="{{route('task.delete',['id'=>$task->getId()])}}">
                    @csrf
                    @method('delete')
                    <div class="form-group">
                        <button type="submit" class="btn btn-dark">Delete task</button>
                    </div>
                     @include('partials.errors')
                </form>
            </div>
        </div>
    </div>


@endsection

resources/views/Tasks/index.blade.php
@extends('partials.layout')

@section('title')
    Tasks
@endsection

@section ('content')
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-12 ">
                <table class=" table table-bordered">
                    <thead class="thead-dark">
                        <tr>
                            <th class="w-25">Title</th>
                            <th class="w-100">Description</th>
                            <th>Completed</th>
                            <th>Remarks</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($tasks as $task)
                            <tr>
                                <td>{{$task->getTitle()}}</td>
                                <td>{{$task->getDescription()}}</td>
                                <td>{{($task->getCompleted())?'Yes':'No'}}</td>
                                <td>{{$task->getRemarksCompleted()}}</td>
                                <td>
                                    <form method="get" action="{{route('task.edit',['id'=>$task->getId()])}}" >
                                        <button type="submit" class="btn btn-success btn-block">Edit task</button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
            <div>
                <form method="GET" action="{{route('task.create')}}">
                    <button type="submit" class="btn btn-success">Create new task</button>
                </form>

            </div>
        </div>
    </div>
@endsection

resources/views/Weeks/create.blade.php
@extends ('partials.layout')

@section('title')
    New week
@endsection

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-12 ">
               <form method = "post" action="{{route("week.store")}}">
                   @csrf
                   <div class="form-group">
                       <label>Week number </label>
                       <input type="text" name="weekNumber" class="form-control" value="{{old('weekNumber')}}">
                   </div>
                   <div class="form-group">
                       <label>Start date </label>
                       <input type="date" name="startDate" class="form-control" value="{{old('startDate')}}">
                   </div>
                   <div class="form-group">
                       <label>End date </label>
                       <input type="date" name="endDate" class="form-control" value="{{old('endDate')}}">
                   </div>
                   <div class="form-group">
                       <button type="submit" class="btn-success">Save Week</button>
                   </div>
                   @include('partials.errors')
               </form>
            </div>
        </div>
    </div>
@endsection

resources/views/Weeks/index.blade.php
@extends ('partials.layout')

@section('title')
    Week
@endsection

@section('content')
    <div class="container mt-3">
        <div class="row">
            <div class="col-lg-8 col-md-12 ">
                <table class=" table table-bordered">
                    <thead class="thead-dark">
                    <tr>
                        <th>Week number</th>
                        <th>Start date</th>
                        <th>End date</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($weeks as $week)
                        <tr>
                            <td class="text-center">{{$week->getWeekNumber()}}</td>
                            <td>{{$week->getStartDate()}}</td>
                            <td>{{$week->getEndDate()}}</td>
                            <td>
                                <form method="get" action="{{route('week.show',['id'=>$week->getId()])}}" >
                                    <button type="submit" class="btn btn-success btn-block">See tasks</button>
                                </form>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
        <div class="row">
            <form method="get" action="{{route('week.create')}}">
                <button type="submit" class="btn btn-success">New week</button>
            </form>
        </div>
    </div>
@endsection

resources/views/Weeks/show.blade.php
@extends ('partials.layout')

@section('title')
    Week/{{$week->getWeekNumber()}}
@endsection

@section ('content')
    <div class="container mt-3">
        <div class="row">
            <div class="col-lg-7">
                <table class="table">
                    <tbody>
                    <tr>
                        <th scope="row">Datum</th>
                        <td>Week {{$week->getWeekNumber()}} van {{$week->getStartDate()}} t.e.m. {{$week->getEndDate()}}</td>
                    </tr>
                    <tr>
                        <th scope="row">geplande taken</th>
                        <td>
                            <ul>
                                @foreach($week->getTasks() as $task)
                                    @if($task->getUser() === \Illuminate\Support\Facades\Auth::user())
                                       <li>
                                           <a href="{{route('task.edit',['id'=>$task->getId()])}}">{{$task->getTitle()}}</a>
                                       </li>
                                    @endif
                                @endforeach
                            </ul>
                        </td>
                    </tr>
                    <tr>
                        <th scope="row">Voltooide taken</th>
                        <td>
                        <ul>
                            @foreach($week->getTasks() as $task)
                                @if($task->getCompleted() == 1 && $task->getUser() === \Illuminate\Support\Facades\Auth::user())
                                <li>
                                    {{$task->getTitle()}}
                                    <br>
                                    <span class="pl-3">{{$task->getRemarksCompleted()}}</span>
                                </li>
                                @endif
                            @endforeach
                        </ul>
                        </td>
                    </tr>
                    </tbody>
                </table>
            </div>
            <div class="col-lg-4 offset-lg-1">
                <h4 class="ml-3">Create a new task for this week</h4>
                <div class="col-lg-10 col-md-6">
                    <form method="post" action="{{route('weekTask',[$id=$week->getId()])}}">
                        @csrf
                        <div class="form-group">
                            <label >Title </label>
                            <input type="text" name="title" class="form-control" required>
                        </div>
                        <div class="form-group">
                            <label >Description </label>
                            <textarea type="text" name="description" class="form-control" required></textarea>
                        </div>
                        <div class="form-group">
                            <button type="submit" class="btn btn-success">Create task</button>
                        </div>
                        @include('partials.errors')
                    </form>
                </div>
            </div>
        </div>
    </div>




@endsection

resources/views/about.blade.php
@extends('partials.layout')

@section ('title')
    About
@endsection

@section ('content')

@endsection

resources/views/contact.blade.php
@extends('partials.layout')

@section ('title')
    Contact
@endsection

@section ('content')

@endsection

resources/views/home.blade.php
@extends('partials.layout')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/partials/errors.blade.php
@if($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach($errors->all() as $error)
                <li>{{$error}}</li>
            @endforeach
        </ul>
    </div>
@endif

resources/views/partials/layout.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>@yield ('title')</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,600" rel="stylesheet">

    <!--Styles -->
    <link href="{{ mix('/css/app.css') }}" rel="stylesheet">
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
@include ('partials.navigation')

@yield ('content')
</body>
</html>

resources/views/partials/navigation.blade.php
<div class="container mb-4">
    <nav class="navbar navbar-expand-sm bg-light">
        <!-- Left Side Of Navbar -->
        <ul class="navbar-nav mr-auto">
            <li class="nav-item"><a class="navbar-brand" href={{route('home')}}>Home</a></li>
            <li class="nav-item"><a class="navbar-brand" href={{route('about')}}>About</a></li>
            <li class="nav-item"><a class="navbar-brand" href={{route('contact')}}>Contact</a></li>
            <li class="nav-item"><a class="navbar-brand" href={{route('week.')}}>Weeks</a></li>
        </ul>

        <!-- Right Side Of Navbar -->
        <ul class="navbar-nav ml-auto">
            <!-- Authentication Links -->
            @guest
                <li class="nav-item">
                    <a class="navbar-brand" href="{{ route('login') }}">Login</a>
                </li>
                @if (Route::has('register'))
                    <li class="nav-item">
                        <a class="navbar-brand" href="{{ route('register') }}">Register</a>
                    </li>
                @endif
            @else
                <li class="nav-item dropdown">
                    <a id="navbarDropdown" class="nav-brand dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                        {{ Auth::user()->getUserName() }} <span class="caret"></span>
                    </a>

                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{{ route('logout') }}"
                           onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                            {{ __('Logout') }}
                        </a>

                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                            @csrf
                        </form>
                    </div>
                </li>
            @endguest
        </ul>
    </nav>
</div>